baseURL = 'https://UnderYourSpell.'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'terminal'

paginate = 5

[params]
  # dir name of your main content (default is `content/posts`).
  # the list of set content will show up on your index page (baseurl).
  contentTypeName = "posts"

  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 3

  # show selector to switch language
  showLanguageSelector = false

  # set theme to full screen width
  fullWidthTheme = false
  # center theme with default width
  centerTheme = false

  # if your resource directory contains an image called `cover.(jpg|png|webp)`,
  # then the file will be used as a cover automatically.
  # With this option you don't have to put the `cover` param in a front-matter.
  autoCover = true

  # set post to show the last updated
  # If you use git, you can set `enableGitInfo` to `true` and then post will automatically get the last updated
  showLastUpdated = false

[languages]
    [languages.en]
        languageName = "English"
        title = "Moro Bamber"

        [languages.en.params]
        subtitle = "A simple, retro theme for Hugo"
        owner = ""
        keywords = ""
        copyright = ""
        menuMore = "Show more"
        readMore = "Read more"
        readOtherPosts = "Read other posts"
        newerPosts = "Newer posts"
        olderPosts = "Older posts"
        missingContentMessage = "Page not found..."
        missingBackButtonLabel = "Back to home page"
        minuteReadingTime = "min read"
        words = "words"

        [languages.en.params.logo]
            logoText = "Moro Bamber"
            logoHomeLink = "/"

        [languages.en.menu]
            [[languages.en.menu.main]]
            identifier = "about"
            name = "About Me"
            url = "/about"
            [[languages.en.menu.main]]
            identifier = "Projects"
            name = "Projects"
            url = "/projects"
            #not added a blog yet
            #[[languages.en.menu.main]]
            #identifier = "blog"
            #name = "Blog"
            #url = "/blog"
